### ISSUE TITLE
WarsawJS (https://twitter.com/warsawjs) (http://warsawjs.com/)

### ISSUE THREAD

**Issue by hinok** [FancyGrid/city-js-community#4]
### Poland
* [Warsaw](http://warsawjs.com) - 350+ followers in [twitter](https://twitter.com/warsawjs)

**Comment by hinok** [comment]
I added PR https://github.com/FancyGrid/city-js-community/pull/5

**Comment by MikhailTatsky** [comment]
Thank you for contributing.
