### ISSUE TITLE
Add Gdańsk to Polish cities

### ISSUE THREAD

**Issue by cojack** [FancyGrid/city-js-community#8]
Hello,
I would like to inform about Gdańs as a part of MeetJS in Poland
MeetJS Gdańsk have over 100+ followers: https://twitter.com/meetjsGdansk
But MeetJS Poland have over 1k followers: https://twitter.com/meetjs

Thanks in advance,
Regards cojack.

P.S. Nice initiative to collect this kind of information in one place.

**Comment by MikhailTatsky** [comment]
Gdańsk was added.

We would like to keep this list only for cities. 
So MeetJS would not be added.

Anyway, thank you.
